name: Java CI - Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Compilar o Projeto
      run: |
          cd src
          javac -cp . Main.java

    - name: Executando o Proejto
      run: |
        cd src
        java -cp . Main
       
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: nisflei/app_padrao
        tags: 1.0
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
